name: aves
description: A visual media gallery and metadata explorer app.
repository: https://github.com/deckerst/aves
version: 1.3.5+41
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

# TODO TLAD merge null safe `expansion_tile_card` to fork
# TODO TLAD migrate from `flushbar` to basic SnackBar or `another_flushbar`
# TODO TLAD migrate from `geocoder` to `geocoding` (or reimplement) - https://github.com/Baseflow/flutter-geocoding/issues/37
# TODO TLAD remove explicit `overlay_support` version when 1.2.0 is stable (1.0.5 uses deprecated `ancestorWidgetOfExactType`)
# TODO TLAD upgrade printing to >=5 when `flutter_driver` dependency upgrade get on the right channel
#   https://github.com/flutter/flutter/pull/75370
#   https://github.com/flutter/flutter/blob/master/packages/flutter_driver/pubspec.yaml
#   otherwise, we get this conundrum:
#     every version of flutter_driver from sdk depends on crypto 2.1.5
#     pdf >=3.0.1 depends on crypto ^3.0.0
#     printing >=5.0.1 depends on pdf ^3.0.1

# not null safe, as of 2021/03/09
# `charts_flutter` - https://github.com/google/charts/issues/579
# `country_code` - unmaintained?
# `decorated_icon` - https://github.com/benPesso/flutter_decorated_icon/issues/2
# `flushbar` - discontinued
# `flutter_ijkplayer` - unmaintained?
# `flutter_map` - https://github.com/fleaflet/flutter_map/issues/829
# `geocoder` - unmaintained? - https://github.com/aloisdeniel/flutter_geocoder/issues/61
# `latlong` - archived - migrate to maps_toolkit? cf https://github.com/fleaflet/flutter_map/pull/750
# `palette_generator` - https://github.com/flutter/packages/pull/287
# `panorama` - no issue/PR
# `streams_channel` - unmaintained? - no issue/PR

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  charts_flutter:
  collection:
  connectivity:
  country_code:
  decorated_icon:
  event_bus:
  expansion_tile_card:
#    path: ../expansion_tile_card
    git:
      url: git://github.com/deckerst/expansion_tile_card.git
  firebase_core:
  firebase_analytics:
  firebase_crashlytics:
  flushbar:
  flutter_highlight:
  flutter_ijkplayer:
#    path: ../flutter_ijkplayer
    git:
      url: git://github.com/deckerst/flutter_ijkplayer.git
  flutter_localized_locales:
  flutter_map:
  flutter_markdown:
  flutter_staggered_animations:
  flutter_svg:
  geocoder:
  github:
  google_api_availability:
  google_maps_flutter:
  intl:
  latlong:
  material_design_icons_flutter:
  overlay_support: 1.2.0-nullsafety.0
  package_info:
  palette_generator:
  panorama:
  pdf:
  pedantic:
  percent_indicator:
  permission_handler:
  printing: 4.1.0
  provider:
  shared_preferences:
  sqflite:
  streams_channel:
  tuple:
  url_launcher:
  version:
  xml:

dependency_overrides:
  # because of `charts_flutter`
  intl: '>=0.17.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test:

flutter:
  assets:
    - assets/
  generate: true
  uses-material-design: true

################################################################################
# Localization

# language files:
# - /lib/l10n/app_{language}.arb
# - /android/app/src/main/res/values-{language}/strings.xml
# - /android/app/src/debug/res/values-{language}/strings.xml (optional)
# - /android/app/src/profile/res/values-{language}/strings.xml (optional)

# generate `AppLocalizations`
# % flutter gen-l10n

# list untranslated messages
# % flutter gen-l10n --untranslated-messages-file untranslated.json

################################################################################
# Test driver

# run (any device):
# % flutter drive -t test_driver/app.dart

# capture shaders in profile mode (real device only):
# % flutter drive -t test_driver/app.dart --profile --cache-sksl --write-sksl-on-exit shaders.sksl.json

################################################################################
# Package study

# brendan-duncan/image (as of v2.1.19):
# - does not support TIFF with JPEG compression (issue #184)
# - TIFF tile decoding is not public (issue #258)

# video_player (as of v0.10.8+2, backed by ExoPlayer):
# - does not support content URIs (by default, but trivial by fork)
# - does not support AVI/XVID, AC3
# - cannot play if only the video or audio stream is supported

# fijkplayer (as of v0.7.1, backed by IJKPlayer & ffmpeg):
# - support content URIs
# - does not support XVID, AC3 (by default, but possible by custom build)
# - can play if only the video or audio stream is supported
# - crash when calling `seekTo` for some files (e.g. TED talk videos)

# flutter_ijkplayer (as of v0.3.5+1, backed by IJKPlayer & ffmpeg):
# - support content URIs (`DataSource.photoManagerUrl` from v0.3.6, but need fork to support content URIs on Android <Q)
# - does not support AC3 (by default, but possible by custom build)
# - can play if only the video or audio stream is supported
