name: aves
description: Aves is a gallery and metadata explorer app, built for Android.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.2+38

# brendan-duncan/image (as of v2.1.19):
# - does not support TIFF with JPEG compression (issue #184)
# - TIFF tile decoding is not public (issue #258)

# video_player (as of v0.10.8+2, backed by ExoPlayer):
# - does not support content URIs (by default, but trivial by fork)
# - does not support AVI/XVID, AC3
# - cannot play if only the video or audio stream is supported

# fijkplayer (as of v0.7.1, backed by IJKPlayer & ffmpeg):
# - support content URIs
# - does not support XVID, AC3 (by default, but possible by custom build)
# - can play if only the video or audio stream is supported
# - crash when calling `seekTo` for some files (e.g. TED talk videos)

# flutter_ijkplayer (as of v0.3.5+1, backed by IJKPlayer & ffmpeg):
# - support content URIs (`DataSource.photoManagerUrl` from v0.3.6, but need fork to support content URIs on Android <Q)
# - does not support AC3 (by default, but possible by custom build)
# - can play if only the video or audio stream is supported

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter:
  collection:
  decorated_icon:
  draggable_scrollbar:
#    path: ../flutter-draggable-scrollbar
    git:
      url: git://github.com/deckerst/flutter-draggable-scrollbar.git
  event_bus:
  expansion_tile_card:
#    path: ../expansion_tile_card
    git:
      url: git://github.com/deckerst/expansion_tile_card.git
  firebase_core:
  firebase_analytics:
  firebase_crashlytics:
  flushbar:
  flutter_highlight:
  flutter_ijkplayer:
#    path: ../flutter_ijkplayer
    git:
      url: git://github.com/deckerst/flutter_ijkplayer.git
  flutter_map:
  flutter_markdown:
  flutter_native_timezone:
  flutter_staggered_animations:
  flutter_svg:
  geocoder:
  google_maps_flutter:
  intl:
  latlong: # for flutter_map
  material_design_icons_flutter:
  overlay_support:
  package_info:
  palette_generator:
  panorama:
  pdf:
  pedantic:
  percent_indicator:
  permission_handler:
  printing:
  provider:
  screen:
  shared_preferences:
  sqflite:
  streams_channel:
  tuple:
  url_launcher:
  xml:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # run on any device:
  # % flutter drive -t test_driver/app.dart
  # capture shaders in profile mode (real device only):
  # % flutter drive -t test_driver/app.dart --profile --cache-sksl --write-sksl-on-exit shaders.sksl.json
  flutter_driver:
    sdk: flutter

  test: any

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Concourse
      fonts:
        - asset: fonts/ConcourseT3-Regular.ttf
    - family: Concourse Caps
      fonts:
        - asset: fonts/ConcourseC3-Regular.ttf
