name: aves
description: A visual media gallery and metadata explorer app.
repository: https://github.com/deckerst/aves
version: 1.4.3+47
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

# not null safe, as of 2021/06/07
# `charts_flutter` - https://github.com/google/charts/issues/579

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  charts_flutter:
  collection:
  connectivity_plus:
  country_code:
  decorated_icon:
  event_bus:
  expansion_tile_card:
    git:
      url: git://github.com/deckerst/expansion_tile_card.git
  fijkplayer:
    git:
      url: git://github.com/deckerst/fijkplayer.git
      ref: aves
  firebase_core:
  firebase_analytics:
  firebase_crashlytics:
  flex_color_picker:
  flutter_highlight:
  flutter_map:
  flutter_markdown:
  flutter_staggered_animations:
  flutter_svg:
  get_it:
  github:
  google_api_availability:
  google_maps_flutter:
  intl:
  latlong2:
  material_design_icons_flutter:
  overlay_support:
  package_info_plus:
  palette_generator:
# TODO TLAD upgrade panorama when this is fixed: https://github.com/zesage/panorama/issues/25 (bug in v0.4.1)
  panorama: 0.4.0
  pdf:
  pedantic:
  percent_indicator:
  permission_handler:
  printing:
  provider:
  shared_preferences:
  sqflite:
  streams_channel:
    git:
      url: git://github.com/deckerst/aves_streams_channel.git
  tuple:
  url_launcher:
  version:
  xml:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test:

flutter:
  assets:
    - assets/
  generate: true
  uses-material-design: true

################################################################################
# Build

# deckerst/fijkplayer

# This fork depends on a local .aar, but Flutter does not support this well
# cf https://github.com/flutter/flutter/issues/28195
# so building an app with this plugin requires the file to be present at:
# `<app-root>/android/app/libs/fijkplayer-full-release.aar`
# The .aar file in the app will take precedence over the one in the plugin itself.

# The reference file is available at:
# - [git] https://github.com/deckerst/fijkplayer/blob/aves-config/android/libs/fijkplayer-full-release.aar
# - [local/win] C:\Users\<user>\AppData\Local\Pub\Cache\git\fijkplayer-<version>\android\libs\fijkplayer-full-release.aar

################################################################################
# Localization

# language files:
# - /lib/l10n/app_{language}.arb
# - /android/app/src/main/res/values-{language}/strings.xml
# - /android/app/src/debug/res/values-{language}/strings.xml (optional)
# - /android/app/src/profile/res/values-{language}/strings.xml (optional)
# - edit locale name resolution for language setting

# generate `AppLocalizations`
# % flutter gen-l10n

################################################################################
# Test driver

# run (any device):
# % flutter drive -t test_driver/app.dart

# capture shaders in profile mode (real device only):
# % flutter drive -t test_driver/app.dart --profile --cache-sksl --write-sksl-on-exit shaders.sksl.json
