name: aves
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  after_init:
  charts_flutter:
  collection:
  draggable_scrollbar:
    git:
      url: git://github.com/deckerst/flutter-draggable-scrollbar.git
  event_bus:
  flushbar:
#   flushbar-1.9.1 cannot be built with Flutter 1.15.17
    git:
      url: https://github.com/AndreHaueisen/flushbar.git
      ref: 13c55a8
  flutter_native_timezone:
  flutter_staggered_grid_view:
  flutter_sticky_header:
    git:
      url: git://github.com/deckerst/flutter_sticky_header.git
  flutter_svg:
  geocoder:
  google_maps_flutter:
  intl:
  logger:
  outline_material_icons:
  path:
  pdf:
  pedantic:
  permission_handler:
  photo_view:
  printing:
  provider:
  screen:
  shared_preferences:
  sqflite:
  transparent_image:
  tuple:
  video_player:
    path: ../plugins/packages/video_player/video_player

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Concourse
      fonts:
        - asset: fonts/ConcourseT3-Regular.ttf
    - family: Concourse Caps
      fonts:
        - asset: fonts/ConcourseC3-Regular.ttf
