name: aves
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

# video_player (as of v0.10.8+2, backed by ExoPlayer):
# - no URI handling by default but trivial by fork
# - support: AVI/XVID/MP3 nothing, MP2T nothing
# - cannot support more formats
# - playable only when both the video and audio streams are supported

# fijkplayer (as of v0.7.1, backed by IJKPlayer & ffmpeg):
# - URI handling
# - support: AVI/XVID/MP3 audio only, MP2T video only
# - possible support for more formats by customizing ffmpeg build,
# - playable when only the video or audio stream is supported
# - crash when calling `seekTo` for some files (e.g. TED talk videos)

# flutter_ijkplayer (as of v0.3.5+1, backed by IJKPlayer & ffmpeg):
# - URI handling (`DataSource.photoManagerUrl` from v0.3.6, but need fork to support content URIs on Android <Q)
# - support: AVI/XVID/MP3 video/audio, MP2T video only
# - possible support for more formats by TODO TLAD customizing ffmpeg build?
# - playable when only the video or audio stream is supported

dependencies:
  flutter:
    sdk: flutter
  after_init:
  charts_flutter:
  collection:
  draggable_scrollbar:
    path: ../flutter-draggable-scrollbar
#    git:
#      url: git://github.com/deckerst/flutter-draggable-scrollbar.git
  event_bus:
  expansion_tile_card:
    path: ../expansion_tile_card
#    git:
#      url: git://github.com/deckerst/expansion_tile_card.git
  flutter_ijkplayer:
    path: ../flutter_ijkplayer
#    git:
#      url: git://github.com/deckerst/flutter_ijkplayer.git
  flushbar:
  flutter_native_timezone:
  flutter_svg:
  geocoder:
  google_maps_flutter:
  intl:
  logger:
  outline_material_icons:
  path:
  pdf:
  palette_generator:
  pedantic:
  percent_indicator:
  permission_handler:
  photo_view:
  printing:
  provider:
  screen:
  shared_preferences:
  sqflite:
  transparent_image:
  tuple:
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Concourse
      fonts:
        - asset: fonts/ConcourseT3-Regular.ttf
    - family: Concourse Caps
      fonts:
        - asset: fonts/ConcourseC3-Regular.ttf
