name: aves
description: A visual media gallery and metadata explorer app.
repository: https://github.com/deckerst/aves
version: 1.3.7+43
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

# TODO TLAD switch to Flutter stable when possible, currently on dev/beta because of the following mess:
# printing >=5.0.1 depends on pdf ^3.0.1, pdf >=3.0.1 depends on crypto ^3.0.0 and archive ^3.1.0
# but `flutter_driver` (shipped with Flutter) dependencies are too old in stable v2.0.1
# bump `crypto` and others - 2021/02/05 https://github.com/flutter/flutter/commit/bc1cf4945841ba5874f5262b8146d52750e7c11f
# bump `archive` from 3.0.0 to 3.1.2 - 2021/03/04 https://github.com/flutter/flutter/commit/ddcb8d7d6d3fcedc906b2f1bf26b73c018d3dc28

# not null safe, as of 2021/03/13
# `charts_flutter` - https://github.com/google/charts/issues/579
# `fijkplayer` - https://github.com/befovy/fijkplayer/issues/381
# `flutter_map` - https://github.com/fleaflet/flutter_map/issues/829
# `latlong` - archived - migrate to maps_toolkit? cf https://github.com/fleaflet/flutter_map/pull/750
# `streams_channel` - unmaintained? - no issue/PR

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  charts_flutter:
  collection:
  connectivity:
  country_code:
  decorated_icon:
  event_bus:
  expansion_tile_card:
    git:
      url: git://github.com/deckerst/expansion_tile_card.git
  fijkplayer:
    git:
      url: git://github.com/deckerst/fijkplayer.git
      ref: aves
  firebase_core:
  firebase_analytics:
  firebase_crashlytics:
  flutter_highlight:
  flutter_localized_locales:
  flutter_map:
  flutter_markdown:
  flutter_staggered_animations:
  flutter_svg:
  get_it:
  github:
  google_api_availability:
  google_maps_flutter:
  intl:
  latlong:
  material_design_icons_flutter:
  overlay_support:
  package_info:
  palette_generator:
  panorama:
  pdf:
  pedantic:
  percent_indicator:
  permission_handler:
  printing:
  provider:
  shared_preferences:
  sqflite:
  streams_channel:
  tuple:
  url_launcher:
  version:
  xml:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test:

flutter:
  assets:
    - assets/
  generate: true
  uses-material-design: true

################################################################################
# Build

# deckerst/fijkplayer

# This fork depends on a local .aar, but Flutter does not support this well
# cf https://github.com/flutter/flutter/issues/28195
# so building an app with this plugin requires the file to be present at:
# `<app-root>/android/app/libs/fijkplayer-full-release.aar`
# The .aar file in the app will take precedence over the one in the plugin itself.

# The reference file is available at:
# - [git] https://github.com/deckerst/fijkplayer/blob/aves-config/android/libs/fijkplayer-full-release.aar
# - [local/win] C:\Users\<user>\AppData\Local\Pub\Cache\git\fijkplayer-<version>\android\libs\fijkplayer-full-release.aar

################################################################################
# Localization

# language files:
# - /lib/l10n/app_{language}.arb
# - /android/app/src/main/res/values-{language}/strings.xml
# - /android/app/src/debug/res/values-{language}/strings.xml (optional)
# - /android/app/src/profile/res/values-{language}/strings.xml (optional)

# generate `AppLocalizations`
# % flutter gen-l10n

################################################################################
# Test driver

# run (any device):
# % flutter drive -t test_driver/app.dart

# capture shaders in profile mode (real device only):
# % flutter drive -t test_driver/app.dart --profile --cache-sksl --write-sksl-on-exit shaders.sksl.json
