name: aves
description: A visual media gallery and metadata explorer app.
repository: https://github.com/deckerst/aves
version: 1.5.4+58
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

# use `scripts/apply_flavor_{flavor}.sh` to set the right dependencies for the flavor
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  aves_report:
    path: plugins/aves_report
  aves_report_platform:
    path: plugins/aves_report_crashlytics
# TODO TLAD as of 2021/10/18, latest version (v0.11.0) is incompatible with Flutter v2.5
  charts_flutter:
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter
  collection:
  connectivity_plus:
  country_code:
# TODO TLAD as of 2021/10/18, null safe version is pre-release
  custom_rounded_rectangle_border: '>=0.2.0-nullsafety.0'
  decorated_icon:
  device_info_plus:
  equatable:
  event_bus:
  expansion_tile_card:
    git:
      url: git://github.com/deckerst/expansion_tile_card.git
  fijkplayer:
    git:
      url: git://github.com/deckerst/fijkplayer.git
      ref: aves
  flex_color_picker:
  fluster:
  flutter_highlight:
  flutter_map:
  flutter_markdown:
  flutter_staggered_animations:
  get_it:
  github:
  google_api_availability:
  google_maps_flutter:
  intl:
  latlong2:
  material_design_icons_flutter:
  overlay_support:
  package_info_plus:
  palette_generator:
# TODO TLAD as of 2021/10/18, latest version (v0.4.1) has this issue: https://github.com/zesage/panorama/issues/25
  panorama: 0.4.0
  pdf:
  percent_indicator:
  permission_handler:
  printing:
  provider:
  shared_preferences:
  sqflite:
  stack_trace:
  streams_channel:
    git:
      url: git://github.com/deckerst/aves_streams_channel.git
  transparent_image:
  tuple:
  url_launcher:
  version:
  xml:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints:
  test:

flutter:
  assets:
    - assets/
  generate: true
  uses-material-design: true

################################################################################
# Build

# deckerst/fijkplayer

# This fork depends on a local .aar, but Flutter does not support this well
# cf https://github.com/flutter/flutter/issues/28195
# so building an app with this plugin requires the file to be present at:
# `<app-root>/android/app/libs/fijkplayer-full-release.aar`
# The .aar file in the app will take precedence over the one in the plugin itself.

# The reference file is available at:
# - [git] https://github.com/deckerst/fijkplayer/blob/aves-config/android/libs/fijkplayer-full-release.aar
# - [local/win] C:\Users\<user>\AppData\Local\Pub\Cache\git\fijkplayer-<version>\android\libs\fijkplayer-full-release.aar

################################################################################
# Localization

# language files:
# - /lib/l10n/app_{language}.arb
# - /android/app/src/main/res/values-{language}/strings.xml
# - edit locale name resolution for language setting

# generate `AppLocalizations`
# % flutter gen-l10n

################################################################################
# Test driver

# run (any device):
# % flutter drive --flavor play -t test_driver/driver_play.dart --profile

# capture shaders in profile mode (real device only):
# % flutter drive --flavor play -t test_driver/driver_play.dart --profile --cache-sksl --write-sksl-on-exit shaders.sksl.json
